version: '3.8'

services:
  db:
    image: postgres:alpine
    volumes:
      - ./db_temp:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: dev

  scrawling:
    image: node:18
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - "8080:8080"
    command:  bash -c "yarn start:api"
    env_file:
      - ./.env